spring:
  application:
    name: zuul
  redis:
    host: localhost
    password:
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
server:
  port: 8080
  servlet:
    session:
      timeout: 3600s
zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      url: http://localhost:8081
      strip-prefix: false
    auth:
      path: /authenticate/**
      url: http://localhost:8081
      strip-prefix: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
