spring:
  application:
    name: zuul
server:
  port: 8080
zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      url: http://localhost:8081
      strip-prefix: false
    auth:
      path: /authenticate/**
      url: http://localhost:8081
      strip-prefix: false
  trace-request-body: true
  include-debug-header: true
  add-proxy-headers: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
